//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindYourMentorProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public int AppointmentID { get; set; }
        public string MenteeName { get; set; }
        public string MenteeState { get; set; }
        public string MenteeAddress { get; set; }
        public int MenteeAge { get; set; }
        public string MenteeContactNo { get; set; }
        public string MenteeEmailID { get; set; }
        public string MenteeWorkingStatus { get; set; }
        public string MenteeGithubID { get; set; }
        public string MenteeLinkedinID { get; set; }
        public string MentorEmailID { get; set; }
        public int AdvertisementID { get; set; }
        public int MenteeID { get; set; }
        public Nullable<System.DateTime> AppointmentDate { get; set; }
        public Nullable<int> StartTime { get; set; }
        public Nullable<int> EndTime { get; set; }
        public int StatusCounter { get; set; }
        public string AppointmentStatus { get; set; }
        public int MentorID { get; set; }
        public Nullable<System.DateTime> AppointmentApplied { get; set; }
        public Nullable<System.DateTime> AppointmentUpdateStatusTime { get; set; }
        public string AppointmentRemoveStatus { get; set; }
        public string AppointmentTime { get; set; }
    
        public virtual CourseAdvertisement CourseAdvertisement { get; set; }
        public virtual RegisterStudent RegisterStudent { get; set; }
    }
}
