//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindYourMentorProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Comment()
        {
            this.ReplyToComments = new HashSet<ReplyToComment>();
        }
    
        public int CommentID { get; set; }
        public int AdvertisementID { get; set; }
        public int MenteeID { get; set; }
        public string Message { get; set; }
        public string mentorName { get; set; }
        public System.DateTime commentedDate { get; set; }
    
        public virtual CourseAdvertisement CourseAdvertisement { get; set; }
        public virtual RegisterStudent RegisterStudent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReplyToComment> ReplyToComments { get; set; }
    }
}
