//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindYourMentorProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fee
    {
        public int FeesID { get; set; }
        public int AdvertisementID { get; set; }
        public int MentorID { get; set; }
        public int MenteeID { get; set; }
        public Nullable<int> Fees { get; set; }
        public string PaymentMode { get; set; }
        public string CardDetails { get; set; }
        public Nullable<int> AmountEntered { get; set; }
        public string PaymentStatus { get; set; }
        public string MenteeEmailID { get; set; }
        public string MentorEmailID { get; set; }
        public string MenteeName { get; set; }
        public string MenteeState { get; set; }
        public string MenteeContactNo { get; set; }
        public Nullable<int> MenteeAge { get; set; }
        public string MenteeLinkedIn { get; set; }
        public string MenteeGitHub { get; set; }
        public Nullable<System.DateTime> PaymentTime { get; set; }
        public Nullable<System.DateTime> StatusUpdateTime { get; set; }
        public string ClassName { get; set; }
        public string CourseName { get; set; }
        public string MentorName { get; set; }
    
        public virtual CourseAdvertisement CourseAdvertisement { get; set; }
        public virtual RegisterStudent RegisterStudent { get; set; }
    }
}
