//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindYourMentorProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback
    {
        public int FeedbackID { get; set; }
        public int AdvertisementID { get; set; }
        public int UserID { get; set; }
        public string Username { get; set; }
        public Nullable<int> Rating { get; set; }
        public string feedbackDescription { get; set; }
        public Nullable<System.DateTime> commentedOn { get; set; }
    
        public virtual CourseAdvertisement CourseAdvertisement { get; set; }
        public virtual CourseAdvertisement CourseAdvertisement1 { get; set; }
        public virtual RegisterStudent RegisterStudent { get; set; }
    }
}
