//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindYourMentorProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegisterMentor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RegisterMentor()
        {
            this.CourseAdvertisements = new HashSet<CourseAdvertisement>();
            ProfilePicture = "~/Image/defaultProfile1.jpg";
        }
    
        public int UserID { get; set; }
        public string Username { get; set; }
        public string EmailID { get; set; }
        public string State { get; set; }
        public Nullable<int> Pincode { get; set; }
        public string ProfilePicture { get; set; }
        public string Password { get; set; }
        public string Description { get; set; }
        public string Role { get; set; }
        public bool IsEmailVerified { get; set; }
        public System.Guid ActivationCode { get; set; }
        public string ResetPasswordCode { get; set; }
        public int Age { get; set; }
        public string ContactNo { get; set; }
        public string Address { get; set; }
        public string GithubID { get; set; }
        public string LinkedinID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CourseAdvertisement> CourseAdvertisements { get; set; }
    }
}
