//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindYourMentorProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReplyToComment
    {
        public int ReplyID { get; set; }
        public int CommentID { get; set; }
        public string Message { get; set; }
        public int AdvertisementID { get; set; }
        public int MenteeID { get; set; }
        public string MentorName { get; set; }
    
        public virtual Comment Comment { get; set; }
        public virtual CourseAdvertisement CourseAdvertisement { get; set; }
        public virtual RegisterStudent RegisterStudent { get; set; }
    }
}
