//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindYourMentorProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SavedList
    {
        public int SavedPostID { get; set; }
        public string ClassName { get; set; }
        public string CourseName { get; set; }
        public string MentorName { get; set; }
        public string Description { get; set; }
        public Nullable<int> BatchesFull { get; set; }
        public Nullable<int> BatchesAvailable { get; set; }
        public int Fees { get; set; }
        public string Address { get; set; }
        public string SpokenLanguage1 { get; set; }
        public string GitHub { get; set; }
        public string Field { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public string SpokenLanguage2 { get; set; }
        public int YearsOfExperience { get; set; }
        public string DemoLec1 { get; set; }
        public string DemoLec2 { get; set; }
        public int MentorID { get; set; }
        public int AdvertisementID { get; set; }
        public int MenteeID { get; set; }
        public string SpokenLanguage3 { get; set; }
        public string SpokenLanguage4 { get; set; }
        public string DemoLec3 { get; set; }
        public string DemoLec4 { get; set; }
        public int TotalSeats { get; set; }
        public int SeatsOccupied { get; set; }
    
        public virtual CourseAdvertisement CourseAdvertisement { get; set; }
        public virtual RegisterStudent RegisterStudent { get; set; }
    }
}
